# Generated by Django 4.0 on 2022-01-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('departure', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('departureDate', models.DateField()),
                ('vehicle', models.CharField(max_length=50)),
                ('vehicleID', models.CharField(max_length=50)),
            ],
        ),
    ]
