# Generated by Django 4.0 on 2022-02-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_loggeduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loggeduser',
            name='id',
        ),
        migrations.AddField(
            model_name='loggeduser',
            name='userid',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
