# Generated by Django 4.0 on 2022-02-07 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_loggeduser_id_loggeduser_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='seat31',
        ),
        migrations.RemoveField(
            model_name='route',
            name='seat32',
        ),
        migrations.RemoveField(
            model_name='route',
            name='seat33',
        ),
        migrations.RemoveField(
            model_name='route',
            name='seat34',
        ),
        migrations.RemoveField(
            model_name='route',
            name='seat35',
        ),
        migrations.RemoveField(
            model_name='route',
            name='seat36',
        ),
    ]
