# Generated by Django 4.0 on 2022-02-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_ticket_amount_ticket_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
