# Generated by Django 4.0 on 2022-02-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_ticket_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='username',
            field=models.CharField(default='dibas', max_length=50),
        ),
    ]
