# Generated by Django 4.0 on 2022-03-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_ticket_arrivaltime_ticket_departuredate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggeduser',
            name='isadmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loggeduser',
            name='loggedin',
            field=models.BooleanField(default=False),
        ),
    ]
