# Generated by Django 4.0 on 2022-03-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_loggeduser_isadmin_loggeduser_loggedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggeduser',
            name='isadmin',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='loggeduser',
            name='loggedin',
            field=models.BooleanField(default=True),
        ),
    ]
