# Generated by Django 4.0 on 2022-04-02 14:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_contact_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='subscribed_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
