# Generated by Django 4.0 on 2022-04-02 14:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_newsletter_subscribed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contacted_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
