# Generated by Django 4.0 on 2022-04-02 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_contact_contacted_date_contact_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='booked_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
