# Generated by Django 3.2.11 on 2022-04-06 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_alter_emailverify_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverify',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
