# Generated by Django 3.2.11 on 2022-04-12 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_loggeduser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggeduser',
            name='id',
            field=models.IntegerField(verbose_name=0),
        ),
    ]
