# Generated by Django 3.2.11 on 2022-04-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_alter_loggeduser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='systeminfo',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='systeminfo',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='systeminfo',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
