# Generated by Django 3.2.11 on 2022-04-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_auto_20220417_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='systeminfo',
            name='paymentapi',
            field=models.CharField(default='', max_length=100),
        ),
    ]
