# Generated by Django 4.0 on 2022-01-28 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_route_departure_remove_route_destination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='vehicleType',
        ),
    ]
